# Generated by Django 4.1.3 on 2022-11-20 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_product_wishlist_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
